config/routes.rb
Rails.application.routes.draw do
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  resources :tasks, except: [:show]
  resources :courses
  resources :roles
  resources :notebooks
  devise_for :users, controllers: {registrations: 'users/registrations' }
  get 'home/index'

  resources :notes

  namespace :admin do
    # get "/stats" => "stats#stats"
    devise_scope :admin_user do
      get '/stats/:scope' => "stats#stats", as: :admin_stats
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticated :user do
    root "notes#index", as: "authenticated_root"
  end

  root "home#index", as: 'unauthenticated_root'
end

app/models/notebook.rb
# == Schema Information
#
# Table name: notebooks
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  course_id  :integer
#

class Notebook < ActiveRecord::Base
  validates :name, presence: true, uniqueness: {scope: :user, case_sensitive: false}
  validates :user_id, presence: true

  has_many :notes, dependent: :restrict_with_error
  belongs_to :user
  belongs_to :course

  delegate :username, to: :user, prefix: true

  def set_notebook_user(user)
    self.user_id = user.id
  end
end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  before_action :set_notebook, only: [:show, :edit, :update, :destroy]
  before_action :own_notebook, only: [:show, :edit, :update, :destroy]
  add_breadcrumb 'Notebooks', :notebooks_path

  respond_to :html, :json, :js

  def index
    @notebooks = policy_scope(Notebook).paginate(page: params[:page], per_page: 10).order('id DESC')
  end

  def show
    add_breadcrumb "#{@notebook.name}", notebook_path
    @notes = Note.where(id: Notebook.find(params[:id]).notes).
        paginate(page: params[:page], per_page: 10).order('id DESC')
  end

  def new
    add_breadcrumb 'New', new_notebook_path
    @notebook = Notebook.new
  end

  def edit
    add_breadcrumb 'Edit', edit_notebook_path
  end

  def create
    @notebook = Notebook.new(notebook_params)
    @notebook.set_notebook_user(current_user)
    flash[:notice] = 'Notebook was successfully created.' if @notebook.save
    respond_with(@notebook)
  end

  def update
    flash[:notice] = 'Notebook was successfully updated.' if @notebook.update(notebook_params)
    respond_with(@notebook)
  end

  def destroy
    if @notebook.destroy
      redirect_to notebooks_url, notice: 'Notebook was successfully destroyed.'
    else
      redirect_to :back, alert: "The notebook #{@notebook.name} has notes."
    end
  end

  private
  def set_notebook
    @notebook = Notebook.find(params[:id])
  end

  def notebook_params
    params.require(:notebook).permit(:name, :user_id, :course_id)
  end

  def own_notebook
    unless current_user == @notebook.user || current_user.role.key = 'admin'
      redirect_to notebooks_url, alert: 'You cannot perform an action on this notebook.'
    end
  end
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/views/notebooks/_form.html.haml
.box
  .box-header
    %h3.box-title
      = notebook.new_record? ? 'New Notebook' : 'Edit Notebook'
  .box-body.pad
    = form_for notebook, layout: :horizontal do |f|
      = f.text_field :name
      .form-group
        %label{class: 'col-sm-3 control-label', for: 'notebook_course'}
          Course
        .col-sm-9
          = f.collection_select(:course_id, policy_scope(Course.all), :id, :name, {prompt: 'Select course'},
                                {class: 'form-control'})
      = f.submit class: 'btn btn-primary'

app/views/notebooks/edit.html.haml
.page-header
  = link_to notebooks_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back

  = link_to notebook_path(@notebook), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show

= render 'form', notebook: @notebook

app/views/notebooks/index.html.haml
.page-header
  = link_to new_notebook_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Notebook

.box
  .box-header.with-border
    %h3.box-title
      Listing Notebooks
  .box-body.table-responsive.no-padding
    %table.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th{rowspan: '1', colspan: '1'} Name
          - if current_user.admin?
            %th{rowspan: '1', colspan: '1'} Username
          %th{rowspan: '1', colspan: '1', style: 'width: 133px; text-align: center;'} Actions

      %tbody
        - @notebooks.each do |notebook|
          %tr.gradeX
            %td= notebook.name
            - if current_user.admin?
              %td= notebook.user_username
            %td
              .btn-group
                .row
                  = link_to '<i class="fa fa-search"></i>'.html_safe, notebook_path(notebook), class: 'btn btn-xs btn-success grow',
                              title: 'Show'
                  = link_to '<i class="fa fa-edit"></i>'.html_safe, edit_notebook_path(notebook),
                              class: 'btn btn-xs btn-primary grow', title: 'Edit'
                  = link_to '<i class="fa fa-trash grow"></i>'.html_safe, notebook_path(notebook),
                               data: { confirm: "Are you sure you want to delete the notebook #{notebook.name}?" },
                               method: :delete, title: 'Delete Notebook', class: 'btn btn-xs btn-danger grow'
  .box-footer.clearfix
    = custom_paginator(@notebooks)

app/views/notebooks/new.html.haml
.page-header
  = link_to notebooks_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back

= render 'form', notebook: @notebook

app/views/notebooks/show.html.haml
.page-header
  = link_to notebooks_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_notebook_path(@notebook), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  = link_to notebook_path(@notebook), class: 'btn btn-danger', title: 'Delete Notebook',
               data: { confirm: "Are you sure you want to delete the notebook #{@notebook.name}?" }, method: :delete do
    %span.glyphicon.glyphicon-remove
    Delete

.col-md-12
  .box
    .box-header.with-border
      %h3.box-title
        = @notebook.name
      .box-tools.pull-right
        %h3.box-title.text-muted
          = @notebook.notes.count
          notes
        %button{class: 'btn btn-box-tool', 'data-widget' => 'collapse'}
          %i.fa.fa-minus
    .box-body.table-responsive.no-padding
      %table.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th{rowspan: '1', colspan: '1'} Title
            %th{rowspan: '1', colspan: '1'} Content
            %th{rowspan: '1', colspan: '1', style: 'width: 133px; text-align: center;'} Actions

        %tbody
          - @notebook.notes.each do |note|
            %tr.gradeX
              %td= note.title
              %td= note.content
              %td
                .btn-group
                  .row
                    = link_to '<i class="fa fa-search"></i>'.html_safe, note_path(note), class: 'btn btn-xs btn-success grow',
                                title: 'Show'
                    = link_to '<i class="fa fa-edit"></i>'.html_safe, edit_note_path(note),
                                class: 'btn btn-xs btn-primary grow', title: 'Edit'
                    = link_to '<i class="fa fa-trash grow"></i>'.html_safe, note_path(note), data: { confirm: 'Are you sure?' },
                                method: :delete, title: 'Delete', class: 'btn btn-xs btn-danger grow'
    .box-footer.clearfix
      = custom_paginator(@notes)