config/routes.rb
Rails.application.routes.draw do
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  resources :tasks, except: [:show]
  resources :courses
  resources :roles
  resources :notebooks
  devise_for :users, controllers: {registrations: 'users/registrations' }
  get 'home/index'

  resources :notes

  namespace :admin do
    # get "/stats" => "stats#stats"
    devise_scope :admin_user do
      get '/stats/:scope' => "stats#stats", as: :admin_stats
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticated :user do
    root "notes#index", as: "authenticated_root"
  end

  root "home#index", as: 'unauthenticated_root'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :own_course, only: [:show, :edit, :update, :destroy]
  add_breadcrumb 'Courses', :courses_path

  respond_to :html, :json, :js

  def index
    @courses = policy_scope(Course).paginate(page: params[:page], per_page: 10).order('id DESC')
  end

  def show
    add_breadcrumb "#{@course.name}", course_path
    @tasks = Task.where(id: Course.find(params[:id]).tasks).
        paginate(page: params[:page], per_page: 10).order('id DESC')
    @notebooks = Notebook.where(id: Course.find(params[:id]).notebooks).
        paginate(page: params[:page], per_page: 10).order('id DESC')
  end

  def new
    add_breadcrumb 'New', new_course_path
    @course = Course.new
  end

  def edit
    add_breadcrumb 'Edit', edit_course_path
  end

  def create
    @course = Course.new(course_params)
    @course.set_course_user(current_user)
    flash[:notice] = 'Course was successfully created.' if @course.save
    respond_with(@course)
  end

  def update
    flash[:notice] = 'Course was successfully updated.' if @course.update(course_params)
    respond_with(@course)
  end

  def destroy
    if @course.destroy
      redirect_to courses_url, notice: 'Course was successfully destroyed.'
    else
      redirect_to :back, alert: "The course #{@course.name} has tasks or notebooks."
    end
  end

  private
  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name, :user_id)
  end

  def own_course
    unless current_user == @course.user || current_user.role.key = 'admin'
      redirect_to courses_url, alert: 'You cannot perform an action on this course.'
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.haml
.box
  .box-header
    %h3.box-title
      = course.new_record? ? 'New Course' : 'Edit Course'
  .box-body.pad
    = form_for course, layout: :horizontal do |f|
      = f.text_field :name
      = f.submit class: 'btn btn-primary'

app/views/courses/edit.html.haml
.page-header
  = link_to courses_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @course, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show

= render 'form', course: @course

app/views/courses/index.html.haml
.page-header
  = link_to new_course_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Course

.box
  .box-header.with-border
    %h3.box-title
      Listing Courses
  .box-body.table-responsive.no-padding
    %table.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th{rowspan: '1', colspan: '1'} Name
          - if current_user.admin?
            %th{rowspan: '1', colspan: '1'} Username
          %th{rowspan: '1', colspan: '1', style: 'width: 133px; text-align: center;'} Actions

      %tbody
        - @courses.each do |course|
          %tr.gradeX
            %td= course.name
            - if current_user.admin?
              %td= course.user_username
            %td
              .btn-group
                .row
                  = link_to '<i class="fa fa-search"></i>'.html_safe, course_path(course), class: 'btn btn-xs btn-success grow',
                              title: 'Show'
                  = link_to '<i class="fa fa-edit"></i>'.html_safe, edit_course_path(course),
                              class: 'btn btn-xs btn-primary grow', title: 'Edit'
                  = link_to '<i class="fa fa-trash grow"></i>'.html_safe, course_path(course),
                              data: { confirm: "Are you sure you want to delete the course #{course.name}?" },
                              method: :delete, title: 'Delete Course', class: 'btn btn-xs btn-danger grow'
  .box-footer.clearfix
    = custom_paginator(@courses)

app/views/courses/new.html.haml
.page-header
  = link_to courses_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back

  = render 'form', course: @course

app/views/courses/show.html.haml
.page-header
  = link_to courses_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_course_path(@course), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  = link_to course_path(@course), class: 'btn btn-danger', title: 'Delete Course',
              data: { confirm: "Are you sure you want to delete the course #{@course.name}?" }, method: :delete do
    %span.glyphicon.glyphicon-remove
    Delete

.col-md-12
  .box
    .box-header.with-border
      %h3.box-title
        = @course.name
.col-md-6
  .box
    .box-header.with-border
      %h3.box-title
        Listing Tasks
      .box-tools.pull-right
        %h3.box-title.text-muted
          = @course.tasks.count
          tasks
        %button{class: 'btn btn-box-tool', 'data-widget' => 'collapse'}
          %i.fa.fa-minus
    .box-body.table-responsive.no-padding
      %table.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th{rowspan: '1', colspan: '1'} Name
            %th{rowspan: '1', colspan: '1'} Deadline date
            %th{rowspan: '1', colspan: '1'} Complete
            - if current_user.admin?
              %th{rowspan: '1', colspan: '1'} Username
            %th{rowspan: '1', colspan: '1', style: 'width: 133px; text-align: center;'} Actions

        %tbody
          - @course.tasks.each do |task|
            %tr.gradeX
              %td= task.name
              %td= task.deadline_date
              %td= task.complete
              - if current_user.admin?
                %td= task.user_username
              %td
                .btn-group
                  .row
                    = link_to '<i class="fa fa-edit"></i>'.html_safe, edit_task_path(task),
                                class: 'btn btn-xs btn-primary grow', title: 'Edit'
                    = link_to '<i class="fa fa-trash grow"></i>'.html_safe, task_path(task),
                                data: { confirm: "Are you sure you want to delete the task #{task.name}?" },
                                method: :delete, title: 'Delete Task', class: 'btn btn-xs btn-danger grow'
    .box-footer.clearfix
      = custom_paginator(@tasks)
.col-md-6
  .box
    .box-header.with-border
      %h3.box-title
        Listing Notebooks
      .box-tools.pull-right
        %h3.box-title.text-muted
          = @course.notebooks.count
          notebooks
        %button{class: 'btn btn-box-tool', 'data-widget' => 'collapse'}
          %i.fa.fa-minus
    .box-body.table-responsive.no-padding
      %table.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th{rowspan: '1', colspan: '1'} Name
            - if current_user.admin?
              %th{rowspan: '1', colspan: '1'} Username
            %th{rowspan: '1', colspan: '1', style: 'width: 133px; text-align: center;'} Actions

        %tbody
          - @course.notebooks.each do |notebook|
            %tr.gradeX
              %td= notebook.name
              - if current_user.admin?
                %td= notebook.user_username
              %td
                .btn-group
                  .row
                    = link_to '<i class="fa fa-search"></i>'.html_safe, notebook_path(notebook), class: 'btn btn-xs btn-success grow',
                                title: 'Show'
                    = link_to '<i class="fa fa-edit"></i>'.html_safe, edit_notebook_path(notebook),
                                class: 'btn btn-xs btn-primary grow', title: 'Edit'
                    = link_to '<i class="fa fa-trash grow"></i>'.html_safe, notebook_path(notebook),
                                 data: { confirm: "Are you sure you want to delete the notebook #{notebook.name}?" },
                                 method: :delete, title: 'Delete Notebook', class: 'btn btn-xs btn-danger grow'
    .box-footer.clearfix
      = custom_paginator(@notebooks)