config/routes.rb
Rails.application.routes.draw do
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  resources :tasks, except: [:show]
  resources :courses
  resources :roles
  resources :notebooks
  devise_for :users, controllers: {registrations: 'users/registrations' }
  get 'home/index'

  resources :notes

  namespace :admin do
    # get "/stats" => "stats#stats"
    devise_scope :admin_user do
      get '/stats/:scope' => "stats#stats", as: :admin_stats
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticated :user do
    root "notes#index", as: "authenticated_root"
  end

  root "home#index", as: 'unauthenticated_root'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :authenticate
  before_action :authenticate_user!

  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protect_from_forgery with: :exception

  def authenticate
    unless ENV['HTTP_AUTH_USERNAME'].blank? or ENV['HTTP_AUTH_PASSWORD'].blank?
      authenticate_or_request_with_http_basic do |username, password|
        username == ENV['HTTP_AUTH_USERNAME'] && password == ENV['HTTP_AUTH_PASSWORD']
      end
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:sign_up) << :role_id
  end

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || authenticated_root_path || unauthenticated_root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash_class(flash_type)
    {success: 'alert-success',
     error: 'alert-danger',
     alert: 'alert-warning',
     notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def custom_paginator(resource)
    will_paginate resource, renderer: BootstrapPagination::Rails, class: 'pagination',
                  next_label: '<i class="fa fa-chevron-right"></i>'.html_safe,
                  previous_label: '<i class="fa fa-chevron-left"></i>'.html_safe
  end

  def page_title
    @title || controller_name.gsub(/Controller/, "").humanize
  end
end

app/views/application/_account_dropdown.html.haml
- if user_signed_in?
  %li.dropdown.user.user-menu
    / Menu Toggle Button
    %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
      / The user image in the navbar
      =image_tag 'user_image', class: 'user-image'
      / hidden-xs hides the username on small devices so only the image appears.
      %span.hidden-xs
        = current_user.username
    %ul.dropdown-menu
      / The user image in the menu
      %li.user-header
        =image_tag 'user_image', class: 'img-circle'
        %p
          = current_user.username
      / Menu Footer
      %li.user-footer
        .pull-left
          =link_to 'Profile', edit_user_path, class: 'btn btn-default btn-flat'
        .pull-right
          =link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-default btn-flat'

app/views/application/_chromeframe.html.haml
/[if lt IE 7 ]
  %p.chromeframe
    You are using an <strong>outdated</strong> browser.
    Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.

app/views/application/_content.html.haml
.content-wrapper
  = render 'flashes'
  / Content Header (Page header)
  %section.content-header
    %ol.breadcrumb
      %li
        %i.fa.fa-dashboard
        = render_breadcrumbs tag: :li, separator: '<i class="fa fa-angle-right" style="padding: 0 5px;"></i>'.html_safe
  / Main content
  %section.content
    = yield

app/views/application/_flashes.html.haml
- unless flash.empty?
  #flash
    - flash.each do |type, message|
      %div{ class: "alert #{bootstrap_flash_class(type)} fade in" }
        = message
        %button.close{ data: { dismiss: 'alert' } } x

app/views/application/_footer.html.haml
%footer.main-footer
  / Default to the left
  %strong
    Copyright © 2015
    = succeed '.' do
      =link_to 'Universidad Autónoma de Chihuahua', 'http://www.uach.mx', target: '_blank'
  Todos los derechos reservados.

app/views/application/_head.html.haml
%head
  %meta{ :charset => 'utf-8' }/
  %meta{ 'http-equiv' => 'X-UA-Compatible', content: 'IE=edge,chrome=1' }/

  = display_meta_tags site: 'UniNotas', title: page_title, reverse: true

  %meta{ name: 'description', content: '' }/
  %meta{ name: 'viewport', content: 'width=device-width' }/

  = render 'stylesheets'
  = javascript_include_tag 'modernizr'

  = csrf_meta_tag

app/views/application/_header.html.haml
%header.main-header
  / Logo
  %a.logo{href: notes_path}
    / mini logo for sidebar mini 50x50 pixels
    %span.logo-mini
      =image_tag 'UNI NOTAS2.png'
    / logo for regular state and mobile devices
    %span.logo-lg
      %b> Uni
      Notas
      =image_tag 'UNI NOTAS2.png'
  / Header Navbar
  %nav.navbar.navbar-static-top{role: "navigation"}
    / Sidebar toggle button
    %a.sidebar-toggle{"data-toggle" => "offcanvas", href: "#", role: "button"}
      %span.sr-only Toggle navigation
    / Navbar Right Menu
    .navbar-custom-menu
      %ul.nav.navbar-nav
        = render 'account_dropdown'

app/views/application/_javascripts.html.haml
= javascript_include_tag 'application'

-#  Append your own using content_for :javascripts
= yield :javascripts

-# Google Analytics
- if !ENV['GOOGLE_ANALYTICS_SITE_ID'].blank?
  :javascript
    var _gaq=[['_setAccount','#{ ENV['GOOGLE_ANALYTICS_SITE_ID'] }'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));

app/views/application/_side_menu.html.haml
%aside.main-sidebar
  / sidebar: style can be found in sidebar.less
  %section.sidebar
    / Sidebar Menu
    %ul.sidebar-menu
      %li.header MENU
      / Optionally, you can add icons to the links
      %li.treeview
        %a{href: '#'}
          %i.fa.fa-file-text
          %span Notes
          %i.fa.fa-angle-left.pull-right
        %ul.treeview-menu
          %li
            =link_to "<i class='fa fa-circle-o'></i> New note".html_safe, new_note_path
          %li
            =link_to "<i class='fa fa-circle-o'></i> All notes".html_safe, notes_path
      %li.treeview
        %a{href: "#"}
          %i.fa.fa-book
          %span Notebooks
          %i.fa.fa-angle-left.pull-right
        %ul.treeview-menu
          %li
            =link_to "<i class='fa fa-circle-o'></i> New notebook".html_safe, new_notebook_path
          %li
            =link_to "<i class='fa fa-circle-o'></i> All notebooks".html_safe, notebooks_path
          - policy_scope(Notebook).all.each do |notebook|
            %li
              =link_to "<i class='fa fa-circle-o'></i> #{notebook.name}".html_safe,
              notebook_path(notebook.id)
      %li.treeview
        %a{href: '#'}
          %i.fa.fa-graduation-cap
          %span Courses
          %i.fa.fa-angle-left.pull-right
        %ul.treeview-menu
          %li
            =link_to "<i class='fa fa-circle-o'></i> New course".html_safe, new_course_path
          %li
            =link_to "<i class='fa fa-circle-o'></i> All courses".html_safe, courses_path
      %li.treeview
        %a{href: '#'}
          %i.fa.fa-tasks
          %span Tasks
          %i.fa.fa-angle-left.pull-right
        %ul.treeview-menu
          %li
            =link_to "<i class='fa fa-circle-o'></i> New task".html_safe, new_task_path
          %li
            =link_to "<i class='fa fa-circle-o'></i> All tasks".html_safe, tasks_path
      - if policy(Role).new? or policy(Role).index?
        %li.header ADMIN
        %li.treeview
          %a{href: '#'}
            %i.fa.fa-user-secret
            %span Roles
            %i.fa.fa-angle-left.pull-right
          %ul.treeview-menu
            %li
              =link_item "<i class='fa fa-circle-o'></i> New role".html_safe, new_role_path
            %li
              =link_item "<i class='fa fa-circle-o'></i> All roles".html_safe, roles_path

app/views/application/_stylesheets.html.haml
= stylesheet_link_tag 'application', :media => nil

-# Append your own using content_for :stylesheets
= yield :stylesheets